### ISSUE TITLE
Consider implementing the `driver.StmtExecContext` interface

### ISSUE THREAD

**Issue by mihaitodor** [microsoft/gocosmos#10]
The [`driver.StmtExecContext` interface](https://pkg.go.dev/database/sql/driver#StmtExecContext) allows users to call [`DB.ExecContext()`](https://pkg.go.dev/database/sql#DB.ExecContext) (and other context-based APIs which use [interface smuggling](https://utcc.utoronto.ca/~cks/space/blog/programming/GoInterfaceSmuggling) - see how that's used [here](https://cs.opensource.google/go/go/+/refs/tags/go1.21.5:src/database/sql/ctxutil.go;l=64) for example). Currently, it looks like the driver is using a default 10s timeout which can be adjusted via the `TIMEOUTMS` field in the connection string, but it would be more flexible to allow users to pass a context for each query which propagates all the way to [`buildJsonRequest()` in `restclient.go`](https://github.com/microsoft/gocosmos/blob/c4c3435bb68819101b2961994bcc99a6b3c7565d/restclient.go#L119) and then [`http.NewRequestWithContext(...)`](https://pkg.go.dev/net/http#NewRequestWithContext) can be used in there instead of `http.NewRequest(...)`.

**Comment by btnguyen2k** [comment]
(partial) improvement has been implemented in v1.1.1
