### ISSUE TITLE
Passing the PartitionKey value for INSERT, UPDATE and DELETE statements

### ISSUE THREAD

**Issue by mihaitodor** [microsoft/gocosmos#9]
Hi @btnguyen2k, thank you very much for putting this driver together and it's awesome to see that it became and official Microsoft release!

I spent a bit of time looking at the code trying to understand what's the best way to integrate it as an additional SQL driver in [Benthos](https://github.com/benthosdev/benthos) so users can leverage the generic `sql_*` components together with CosmosDB. While I am able to get it to work (for basic queries at least), I bumped into a particularity of this driver related to how it extracts the value of the PartitionKey from the variadic args which get passed to `sql.DB.Exec()`, where it seems to mandate that this value gets passed as the last argument. For example, if I have this query `INSERT INTO users (department, name, username, email) VALUES ($1, $2, $3, $4)`, where `/department` is the PartitionKey, then I have to call `db.Exec("<query>", "some_department", "foobar", "foobar_user", "foobar@benthos.dev", "some_department")`. This repetition of the PartitionKey value is awkward because the other SQL drivers I've used require that the number of args match the number of placeholders, which makes it easy to have higher level constructs without adding custom handling for each specific driver.

I don't have a good understanding of the constraints and, assuming it's not ideal (performance might be an issue) to query the server for the container PartitionKey (or Keys when the container uses hierarchical partition keys), I wonder if it would be possible to provide a hint in the query itself to describe which field(s) need to be passed in the `x-ms-documentdb-partitionkey` header and then have the driver pick them out automatically either from the `sql.DB.Exec()` args or directly from the parsed query if its static (doesn't have a placeholder for the PartitionKey(s)). It's a bit unclear why the server needs to receive this header in the first place as suggested in the answer [here](https://stackoverflow.com/questions/57829268/use-of-x-ms-documentdb-partitionkey-on-create/57831549#57831549), but I suppose that's a different discussion.

**Comment by btnguyen2k** [comment]
Hi @mihaitodor,

Your feedback taken. In fact, I have been thinking of a good solution for this issue as well. However, no good solution has come yet. One solution is to query Cosmos DB server for table metadata in order to detect PK automatically, but it'll be a performance penalty. Also, it may incur extra cost as some RU is consumed.
Another approach that I am thinking is to provide a hint to the query using `WITH` clause, for example `INSERT INTO users (department, name, username, email) VALUES ($1, $2, $3, $4) WITH pk=/department`.
The solution will be in the next (maybe a couple) release once I finalize the solution.
 
Best regards,
Thanh

**Comment by mihaitodor** [comment]
Thank you for the quick reply @btnguyen2k! That does help clarify things. I'd be happy with both of those options, since they'd be transparent from the perspective of Benthos. If you only provide the second approach, then the generic `sql_insert` that Benthos provides won't know how to construct the INSERT query automatically, so then I'd only enable it for the `sql_raw` components, where the users would have to always write the full query themselves, but that's not a huge issue.

No rush on this, so please take your time! Until then, I'm adding an input and output based on `github.com/Azure/azure-sdk-for-go`.

**Comment by btnguyen2k** [comment]
This has been implemented in [v1.1.0](https://github.com/microsoft/gocosmos/releases/tag/v1.1.0).

Cheers,

**Comment by mihaitodor** [comment]
@btnguyen2k Awesome job! It works great, at least for my initial experiments. Thank you very much!

I put together a Benthos [PR](https://github.com/benthosdev/benthos/pull/2358) to integrate both https://github.com/Azure/azure-sdk-for-go/sdk/data/azcosmos and this one. There will be some overlap in functionality, but I think this offers the most flexibility, especially since your driver already has some support for hierarchical partition keys and cross-partition queries. A new release is due soon, so hopefully it will make it into that.
